# Generated by Django 6.1 on 2026-08-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdeployment',
            name='welcome_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agentdeployment',
            name='widget_primary_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agentdeployment',
            name='widget_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
