# Generated by Django 6.1 on 2026-08-27 19:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System'), ('TOOL', 'Tool')], max_length=16)),
                ('content', models.TextField()),
                ('tool_call_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PhoneCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_call_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], default='INBOUND', max_length=16)),
                ('caller_number', models.CharField(blank=True, default='', max_length=50)),
                ('recording_url', models.TextField(blank=True, null=True)),
                ('provider_status', models.CharField(choices=[('RINGING', 'Ringing'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TRANSFERRED', 'Transferred')], db_index=True, default='RINGING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('phone', 'phone'), ('website', 'website'), ('api', 'api')], db_index=True, default='phone', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=16)),
                ('outcome', models.CharField(blank=True, choices=[('APPOINTMENT_BOOKED', 'Appointment booked'), ('APPOINTMENT_REQUESTED', 'Appointment requested'), ('INFORMATION_PROVIDED', 'Information provided'), ('CALLBACK_REQUESTED', 'Callback requested'), ('TRANSFERRED_TO_HUMAN', 'Transferred to human'), ('NO_RESOLUTION', 'No resolution'), ('CUSTOMER_HUNG_UP', 'Customer hung up'), ('UNKNOWN', 'Unknown')], max_length=32, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='agents.agent')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
