# Generated by Django 6.1 on 2026-08-27 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0002_initial'),
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecall',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='telephony.phonenumber'),
        ),
    ]
