# Generated by Django 6.1 on 2026-08-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, help_text='Web/API visitor session id, so a returning visitor continues the same open conversation.', max_length=128, null=True),
        ),
    ]
