# Generated by Django 6.1 on 2026-08-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Weekly open schedule keyed by ISO weekday 1 (Mon)..7 (Sun), each an object like {"start": "09:00", "end": "17:00"}. Absent days are closed. An empty dict means always open.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='website_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
