# Generated by Django 6.1 on 2026-08-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_organization_address_organization_business_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='transfer_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
