# Generated by Django 6.1 on 2026-08-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentdeployment_welcome_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='after_hours_behavior',
            field=models.CharField(choices=[('continue', 'Continue with AI'), ('message', 'Message and end call')], default='message', max_length=24),
        ),
        migrations.AddField(
            model_name='agent',
            name='can_transfer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='max_call_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='recording_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='voice_greeting',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
