# Generated by Django 6.1 on 2026-08-30 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('provider_number_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='agents.agent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='tenancy.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
