# Generated by Django 6.1 on 2026-08-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='inbound_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='outbound_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='provider',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('telnyx', 'Telnyx'), ('other', 'Other')], default='twilio', max_length=50),
        ),
    ]
