# Generated by Django 6.1 on 2026-08-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('links', models.JSONField(blank=True, default=list, help_text='List of {label, url} objects.')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('sections', models.JSONField(blank=True, default=list, help_text='Ordered list of {key, enabled}. Keys from SECTION_LABELS.')),
                ('hero_enabled', models.BooleanField(default=True)),
                ('hero_badge', models.CharField(blank=True, default='', max_length=255)),
                ('hero_title', models.CharField(default='Your AI employee for every customer conversation.', max_length=255)),
                ('hero_subtitle', models.TextField(default='Answer calls, chat with website visitors, book appointments, qualify customers, and hand off to your team — automatically.')),
                ('hero_primary_cta', models.CharField(default='Create your AI agent', max_length=64)),
                ('hero_secondary_cta', models.CharField(default='See how it works', max_length=64)),
                ('value_strip_title', models.CharField(default='One AI agent. Every customer channel.', max_length=255)),
                ('value_strip_items', models.JSONField(blank=True, default=list, help_text='List of short channel labels, e.g. PHONE, WEBSITE, APPOINTMENTS.')),
                ('problem_title', models.CharField(default="Your team shouldn't have to answer the same questions all day.", max_length=255)),
                ('problem_items', models.JSONField(blank=True, default=list, help_text='List of common business problems.')),
                ('solution_title', models.CharField(default='Let your AI agent handle the routine. Let your team handle what matters.', max_length=255)),
                ('solution_text', models.TextField(default='Your AI agent answers the repetitive questions, books appointments, and captures every lead — then hands the conversations that matter to your team.')),
                ('features_title', models.CharField(default='Everything a great receptionist does, on autopilot.', max_length=255)),
                ('features_subtitle', models.TextField(default='Purpose-built tools that turn one AI agent into your busiest employee.')),
                ('showcase_title', models.CharField(default='Everything your AI employee needs to run the conversation.', max_length=255)),
                ('showcase_subtitle', models.TextField(default='Calls, customers, appointments, agent and analytics — from one clean workspace.')),
                ('how_works_title', models.CharField(default='How it works', max_length=255)),
                ('how_works_steps', models.JSONField(blank=True, default=list, help_text='List of {num, title, text} steps.')),
                ('website_section_title', models.CharField(default='Put your AI agent on your website in minutes.', max_length=255)),
                ('website_section_text', models.TextField(default='Copy one snippet, paste it before </body>, and your agent is live.')),
                ('website_section_cta', models.CharField(default='Create website agent', max_length=64)),
                ('phone_section_title', models.CharField(default='Never miss a customer call again.', max_length=255)),
                ('phone_section_text', models.TextField(default='Your agent answers, greets, converses, books, and transfers — on your schedule.')),
                ('phone_section_cta', models.CharField(default='Set up phone agent', max_length=64)),
                ('use_cases_title', models.CharField(default='Built for the way service businesses work.', max_length=255)),
                ('use_cases_subtitle', models.TextField(default='Configure your agent for the questions your customers actually ask.')),
                ('analytics_title', models.CharField(default='Know what happened on every conversation.', max_length=255)),
                ('analytics_subtitle', models.TextField(default='Conversations, appointments, transfers and outcomes — all in one view.')),
                ('pricing_title', models.CharField(default='Simple pricing for every stage.', max_length=255)),
                ('pricing_subtitle', models.TextField(default='Pricing coming soon. Start free while you set up.')),
                ('pricing_disclaimer', models.CharField(blank=True, default='', max_length=500)),
                ('faq_title', models.CharField(default='Frequently asked questions', max_length=255)),
                ('faq_subtitle', models.TextField(blank=True, default='')),
                ('cta_title', models.CharField(default='Give your business an AI employee.', max_length=255)),
                ('cta_subtitle', models.TextField(default='Start with one agent. Connect your business. Let it handle the conversations.')),
                ('cta_primary', models.CharField(default='Create your AI agent', max_length=64)),
                ('cta_secondary', models.CharField(default='View demo', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('price', models.CharField(default='Coming soon', max_length=128)),
                ('billing_period', models.CharField(blank=True, default='', max_length=64)),
                ('features', models.JSONField(blank=True, default=list)),
                ('cta_text', models.CharField(default='Get started', max_length=64)),
                ('highlighted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('site_name', models.CharField(default='AI Call Agent', max_length=255)),
                ('logo', models.CharField(blank=True, default='', max_length=500)),
                ('favicon', models.CharField(blank=True, default='', max_length=500)),
                ('font_family', models.CharField(choices=[('Inter', 'Inter'), ('System', 'System')], default='Inter', max_length=64)),
                ('primary_color', models.CharField(default='#2E7CF6', max_length=20)),
                ('secondary_color', models.CharField(default='#14B8A6', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('social_links', models.JSONField(blank=True, default=list, help_text='List of {label, url} objects.')),
                ('announcement_enabled', models.BooleanField(default=False)),
                ('announcement_text', models.CharField(blank=True, default='', max_length=500)),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_description', models.TextField(blank=True, default='')),
                ('og_image', models.CharField(blank=True, default='', max_length=500)),
                ('canonical_url', models.CharField(blank=True, default='', max_length=500)),
                ('robots', models.CharField(default='index,follow', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('quote', models.TextField()),
                ('avatar', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
