# Generated by Django 6.1 on 2026-08-30 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.cms.publishing import ensure_initial_version


def _seed_initial_version(apps, schema_editor):
    """Snapshot the already-seeded published site as version 1.

    After this migration the public API always reads from a published snapshot,
    so future edits are drafts until an explicit publish.
    """
    ensure_initial_version()


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_seed_default_cms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='website_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='CmsActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('draft_saved', 'Draft saved'), ('sections_updated', 'Sections updated'), ('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('restored', 'Version restored')], max_length=32)),
                ('resource', models.CharField(max_length=255)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CmsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Serialized site settings, landing page and ordered collections.')),
                ('is_current', models.BooleanField(default=False)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_versions_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.RunPython(_seed_initial_version, _noop),
    ]
