# Generated by Django 6.1 on 2026-08-30 19:28

from django.db import migrations, models

from apps.cms.publishing import ensure_initial_version


def insert_api_section(apps, schema_editor):
    """Make the new 'api' section visible on drafts that predate it."""
    LandingPage = apps.get_model("cms", "LandingPage")
    page = LandingPage.objects.filter(pk=1).first()
    if page is None:
        return
    sections = list(page.sections or [])
    if any(isinstance(s, dict) and s.get("key") == "api" for s in sections):
        return
    default = {"key": "api", "enabled": True}
    phone_indexes = [
        i for i, s in enumerate(sections)
        if isinstance(s, dict) and s.get("key") == "phone"
    ]
    position = phone_indexes[-1] + 1 if phone_indexes else len(sections)
    sections.insert(position, default)
    page.sections = sections
    page.save(update_fields=["sections", "updated_at"])


def bootstrap_initial_version(apps, schema_editor):
    """Create snapshot v1 for fresh databases.

    Migration 0003 skipped the initial snapshot on fresh databases because the
    ``api_section_*`` columns did not exist yet. Now that they do, finish the
    job; migrated databases already have v1 and are left untouched.
    """
    ensure_initial_version()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_sitesettings_website_url_cmsactivity_cmsversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='api_section_cta',
            field=models.CharField(default='Explore the API', max_length=64),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='api_section_text',
            field=models.TextField(default='Expose your agent as a conversation API. Custom apps, CRMs and support tools can hand conversations to your AI — no phone number or website needed.'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='api_section_title',
            field=models.CharField(default='Put your AI agent inside your own products.', max_length=255),
        ),
        migrations.RunPython(insert_api_section, migrations.RunPython.noop),
        migrations.RunPython(bootstrap_initial_version, migrations.RunPython.noop),
    ]
