# Generated by Django 6.1 on 2026-08-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_landingpage_api_section_cta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='hero_primary_cta',
            field=models.CharField(default='Start for free', max_length=64),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_secondary_cta',
            field=models.CharField(default='Book a demo', max_length=64),
        ),
    ]
