# Generated by Django 6.1 on 2026-08-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversation_visitor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecall',
            name='stream_token',
            field=models.CharField(blank=True, db_index=True, help_text='Per-call secret embedded in the Twilio media stream URL so an unauthenticated websocket cannot open a stream for a call it does not own.', max_length=64, null=True),
        ),
    ]
