"""add tool_call_id and ordering index to call_messages

Revision ID: 44551450a9f8
Revises: fe389e8f0c60
Create Date: 2026-08-27 12:07:02.526769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44551450a9f8'
down_revision: Union[str, Sequence[str], None] = 'fe389e8f0c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_messages', sa.Column('tool_call_id', sa.String(length=100), nullable=True))
    op.create_index('ix_call_messages_call_created', 'call_messages', ['call_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_call_messages_tool_call_id'), 'call_messages', ['tool_call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_messages_tool_call_id'), table_name='call_messages')
    op.drop_index('ix_call_messages_call_created', table_name='call_messages')
    op.drop_column('call_messages', 'tool_call_id')
    # ### end Alembic commands ###
