"""add phone number ownership and provider id

Revision ID: c7d320055359
Revises: fc47c43f3798
Create Date: 2026-08-27 13:12:17.462248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d320055359'
down_revision: Union[str, Sequence[str], None] = 'fc47c43f3798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_numbers', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('phone_numbers', sa.Column('provider_number_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_phone_numbers_owner_id'), 'phone_numbers', ['owner_id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_provider_number_id'), 'phone_numbers', ['provider_number_id'], unique=False)
    op.create_foreign_key(None, 'phone_numbers', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone_numbers', type_='foreignkey')
    op.drop_index(op.f('ix_phone_numbers_provider_number_id'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_owner_id'), table_name='phone_numbers')
    op.drop_column('phone_numbers', 'provider_number_id')
    op.drop_column('phone_numbers', 'owner_id')
    # ### end Alembic commands ###
