# Generated by Django 6.1 on 2026-08-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super admin'), ('PLATFORM_ADMIN', 'Platform admin'), ('SUPPORT_ADMIN', 'Support admin'), ('CONTENT_ADMIN', 'Content admin')], default='', help_text='Platform-level role. Empty means a normal business user.', max_length=32),
        ),
    ]
