"""add call outcome

Revision ID: e05ec9ad05b5
Revises: db54ddbc4181
Create Date: 2026-08-27 12:01:48.638241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05ec9ad05b5'
down_revision: Union[str, Sequence[str], None] = 'db54ddbc4181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    call_outcome = sa.Enum(
        'APPOINTMENT_BOOKED',
        'APPOINTMENT_REQUESTED',
        'INFORMATION_PROVIDED',
        'CALLBACK_REQUESTED',
        'TRANSFERRED_TO_HUMAN',
        'NO_RESOLUTION',
        'CUSTOMER_HUNG_UP',
        'UNKNOWN',
        name='calloutcome',
    )
    call_outcome.create(op.get_bind(), checkfirst=True)
    op.add_column('calls', sa.Column('outcome', call_outcome, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'outcome')
    sa.Enum(name='calloutcome').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
