"""add customer owner and scoped phone uniqueness

Revision ID: fe389e8f0c60
Revises: e05ec9ad05b5
Create Date: 2026-08-27 12:05:04.106953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe389e8f0c60'
down_revision: Union[str, Sequence[str], None] = 'e05ec9ad05b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=False)
    op.create_index(op.f('ix_customers_owner_id'), 'customers', ['owner_id'], unique=False)
    op.create_unique_constraint('uq_customer_owner_phone', 'customers', ['owner_id', 'phone_number'])
    op.create_foreign_key(None, 'customers', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint('uq_customer_owner_phone', 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_owner_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=True)
    op.drop_column('customers', 'owner_id')
    # ### end Alembic commands ###
